### ISSUE TITLE
Tagged release

### ISSUE THREAD

**Issue by awvwgk** [urbanjost/prep#1]
Is there interest in packaging prep? With a tagged release it would be easy to create packages in conda-forge for similar to allow users to easily install binary packages (fpm install is simple, but might be still an additional step).

**Comment by urbanjost** [comment]
I am interested in it, but not sure if a user base is, unfortunately.  I was hoping for fpm plugins like fpm-man, fpm-search, ... and tools like prep to have garnered more interest, and  something like an eco-system emerging where you could say "install a Fortran environment" and get a compiler, package manager, Fortran documentation, and preprocessing, and so on.  

It would not hurt and might increase use. Do you need added to the prep repository or need me to assign a tag or just wanted to know if I thought it was OK or ???  Not really familiar with the process.

**Comment by awvwgk** [comment]
I tend to package projects to assess their stability, if they are hard to package, they are probably harder to use. Also, many tend to break down if more than one platform is targeted.

Packaging works best from some fixed point, *i.e.* a git tag with defined version. Usually this is all what is needed. IMO projects with releases make the impression of being more stable to use, rather than just having a potential continuously moving git repo as reference.

**Comment by awvwgk** [comment]
> I was hoping for fpm plugins like fpm-man, fpm-search, ... and tools like prep to have garnered more interest

Writing tutorials / recipes in the fpm documentation might help, for prep we could have a tutorial as well once we have first class preprocessor support in fpm.
